# Generated by Django 5.1 on 2024-10-09 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blaashapp', '0003_collection_engagement_post_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EngagementPostCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_in_seconds', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EngagementPostContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blaashapp.engagementpost')),
            ],
        ),
        migrations.CreateModel(
            name='EngagementPostProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blaashapp.engagementpost')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('sku', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='engagement_post_content',
            name='engangementpost',
        ),
        migrations.RemoveField(
            model_name='engagement_post_product_mapping',
            name='engagementpost',
        ),
        migrations.RemoveField(
            model_name='engagement_post_collection',
            name='engagementpost',
        ),
        migrations.RemoveField(
            model_name='engagement_post_collection',
            name='collection',
        ),
        migrations.DeleteModel(
            name='engagement_post_product',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='collection_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='engagementpostcollection',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blaashapp.collection'),
        ),
        migrations.AddField(
            model_name='engagementpostcollection',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blaashapp.engagementpost'),
        ),
        migrations.AddField(
            model_name='engagementpostproductmapping',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blaashapp.product'),
        ),
        migrations.DeleteModel(
            name='engagement_post_content',
        ),
        migrations.DeleteModel(
            name='engagement_post_product_mapping',
        ),
        migrations.DeleteModel(
            name='engagement_post',
        ),
        migrations.DeleteModel(
            name='engagement_post_collection',
        ),
    ]
